// src/modules/customer-relationship-management/customer-hub/inventory-report/utils/exportExcel.ts
import * as XLSX from "xlsx";
import { groupInventoryRows, formatBoxQty } from "./groupInventory";
import type { InventoryRow } from "../type";

/**
 * Export inventory data to Excel.
 *
 * Values for Available / Current / Allocated / Inbound / Projected are derived
 * from the same groupInventoryRows() + analyzeGroup() pipeline used by
 * InventoryReportTable, so the exported numbers always match what the user sees
 * on screen.
 */
export function exportToExcel(
  rows: InventoryRow[],
  filename = "inventory-report.xlsx",
  opts?: { filters?: unknown; generatedBy?: string; generatedDate?: string },
) {
  // -------------------------------------------------------------------------
  // Determine which columns to hide based on active filters (same logic as PDF)
  // -------------------------------------------------------------------------
  const filtersObj = opts?.filters as Record<string, unknown> | undefined;

  const isFilterActive = (key: string): boolean => {
    if (!filtersObj) return false;
    const val = filtersObj[key];
    if (val === undefined || val === null) return false;
    if (Array.isArray(val)) {
      return (val as unknown[])
        .map((v) => String(v).trim().toLowerCase())
        .some((v) => v !== "" && v !== "all");
    }
    const s = String(val).trim().toLowerCase();
    return s !== "" && s !== "all";
  };

  const hideBranch = isFilterActive("branch");
  const hideSupplier = isFilterActive("supplier");
  const hideCategory = isFilterActive("category");
  // When brand filter is active, hide both Brand and Unit columns (mirrors PDF exporter)
  const hideBrandAndUnit = isFilterActive("brand");

  // -------------------------------------------------------------------------
  // Group rows exactly as the table does, then flatten to one row per product
  // -------------------------------------------------------------------------
  const groups = groupInventoryRows(rows);

  type ExportRow = Record<string, string | number | null>;
  const data: ExportRow[] = groups.map((g) => {
    const a = g.analysis;
    const row: ExportRow = {};

    row["Product"] = g.productName || "-";
    if (!hideBrandAndUnit) row["Unit"] = g.unit || "-";
    if (!hideBranch) row["Branch"] = g.branch || "-";
    if (!hideSupplier) row["Supplier"] = g.supplier || "-";
    if (!hideCategory) row["Category"] = g.category || "-";
    if (!hideBrandAndUnit) row["Brand"] = g.brand || "-";

    // Numeric columns — using the same box-converted values as the table
    row["Available"] = parseFloat(formatBoxQty(a.availableBoxes));
    row["Current"] = parseFloat(formatBoxQty(a.boxesCurrent));
    row["Allocated"] = parseFloat(formatBoxQty(a.boxesAllocated));
    // NOTE: column labels match the UI headers intentionally:
    //   "Inbound" label  → boxesInbound  (what flows in)
    //   "Projected"      → projectedBoxes (current - allocated + inbound)
    row["Inbound"] = parseFloat(formatBoxQty(a.boxesInbound));
    row["Projected"] = parseFloat(formatBoxQty(a.projectedBoxes));

    return row;
  });

  // Preferred column order (only include columns that weren't hidden)
  const preferredOrder = [
    "Product",
    ...(!hideBrandAndUnit ? ["Unit"] : []),
    ...(!hideBranch ? ["Branch"] : []),
    ...(!hideSupplier ? ["Supplier"] : []),
    ...(!hideCategory ? ["Category"] : []),
    ...(!hideBrandAndUnit ? ["Brand"] : []),
    "Available",
    "Current",
    "Allocated",
    "Inbound",
    "Projected",
  ];

  // -------------------------------------------------------------------------
  // Build array-of-arrays with metadata header rows
  // -------------------------------------------------------------------------
  const generatedBy = opts?.generatedBy ?? "System";
  const generatedDate =
    opts?.generatedDate ??
    new Date().toLocaleString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });

  const rowsAoA: Array<Array<unknown>> = [];
  rowsAoA.push(["Generated By:", generatedBy]);
  rowsAoA.push(["Generated Date:", generatedDate]);

  if (opts?.filters) {
    rowsAoA.push(["Filters:"]);
    for (const [k, v] of Object.entries(opts.filters as Record<string, unknown>)) {
      rowsAoA.push([`${k} = ${Array.isArray(v) ? (v as unknown[]).join(", ") : String(v ?? "All")}`]);
    }
    rowsAoA.push([]); // blank spacer before header
  }

  // Column header row
  rowsAoA.push(preferredOrder);

  // Data rows
  for (const r of data) {
    rowsAoA.push(preferredOrder.map((k) => r[k] ?? null));
  }

  // -------------------------------------------------------------------------
  // Build worksheet
  // -------------------------------------------------------------------------
  const ws = XLSX.utils.aoa_to_sheet(rowsAoA);
  const sheet = ws as unknown as Record<string, unknown>;

  // Column widths
  const numericCols = new Set(["Available", "Current", "Allocated", "Inbound", "Projected"]);
  sheet["!cols"] = preferredOrder.map((k) => {
    if (k === "Product") return { wch: 40 };
    if (numericCols.has(k)) return { wch: 14 };
    if (k === "Unit" || k === "Branch") return { wch: 16 };
    return { wch: 22 };
  });

  sheet["!pageSetup"] = {
    fitToWidth: 1,
    fitToHeight: 1,
    orientation: "landscape",
  };

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Inventory");

  // Optional Filters sheet
  if (opts?.filters) {
    const entries = Object.entries(opts.filters as Record<string, unknown>).map(([k, v]) => [
      k,
      Array.isArray(v) ? (v as unknown[]).join(", ") : String(v ?? ""),
    ]);
    const filterSheet = XLSX.utils.aoa_to_sheet([["Filter", "Value"], ...entries]);
    (filterSheet as unknown as Record<string, unknown>)["!cols"] = [{ wch: 30 }, { wch: 50 }];
    XLSX.utils.book_append_sheet(wb, filterSheet, "Filters");
  }

  XLSX.writeFile(wb, filename);
}

export default exportToExcel;